export { default as Navbar } from './Navbar'
export { default as Homepage} from './pages/Homepage'
export { default as Exchanges} from './pages/Exchanges'
export { default as News} from './pages/News'
export { default as Cryptocurrencies} from './pages/Cryptocurrencies'
export { default as Cryptodetails } from './pages/Cryptodetail'
export {default as Loader} from '../UI/loader'